name: 'Upsert Fleet'
description: 'Upsert a fleet configuration in Shipyard using a YAML file.'
inputs:
  org_id:
    description: 'Organization ID'
    required: true
  project_id:
    description: 'Project ID'
    required: true
  yaml_path:
    description: 'Path to the YAML file containing fleet configuration'
    required: true
  shipyard_api_key:
    description: 'The API key to authenticate with Shipyard.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SHIPYARD_API_KEY: ${{ inputs.shipyard_api_key }}
    ORG_ID: ${{ inputs.org_id }}
    PROJECT_ID: ${{ inputs.project_id }}
    YAML_PATH: ${{ inputs.yaml_path }}
